train:
  epoch: 100
  stage_epoch: 50
  base_model: False
  fine_tune: False
  batch_size: 128
  learning_rate: 0.0005
  weight_decay: 0.0003

energy:
  lambda_d_0: 25.0
  lambda_r_0: 25.0
  lambda_c_0: 1.0
  lambda_d_ft: 35.0
  lambda_r_ft: 25.0
  lambda_c_ft: 1.0

model:
  image_size: 65
  hidden_dim: 16
  output_dim: 128
  layers: 2
